### PR TITLE
Rework the whole project

### PR DESCRIPTION
**Pull request by Bengt**
This pull requests collects my efforts to raise the quality of this project by applying some best practices. As I do not know your workflow, these might not meet your necessities. Please consider my changes as a suggestion and feel free to cherry-pick any of them.

### CODE REVIEW

**Comment by Bengt** [comment]
The path handling poses some challenges for me. @kahst could you maybe check or fix the residual issues?

**Comment by kahst** [comment]
Whoa...there's a LOT to digest :) Thanks for all the work you put into it, we'll take a look.

**Comment by Josef-Haupt** [comment]
Hi, thanks for your contribution!
I haven't looked through all the changes, but a few points from my side:
* the `List` type does not have to be imported manually, starting with Python 3.9 the default `list` can be used the same way
* I remember I had a discussion about splitting all functions into their own files at my old job, honestly I don't see the benefit. It just clutters the directory and works against most editors search functionalities. Can you point me to the style guide that recommands this?
* I would remove the usage of `numpy` instead of `np`, since this has become the standart in every code i've seen so far
* To use consistant naming in files, functions and variables makes sense to me
* More type hints is always nice
* tests are also very nice

**Comment by Bengt** [comment]
@kahst, thanks for your general openness for contributions. That motivates me to revise my changes.

@Josef-Haupt, thanks for pointing out some possible improvements.

- Yes, in fact, all the aliases for built-in types are now deprecated. Since BirdNET only supports Python 3.9 and later, we can use the built-ins exclusively. From what I remember, there is at least some usage of those in this code base. I will take a look and revise that later. https://docs.python.org/3/library/typing.html#aliases-to-built-in-types

- The most tangible benefit of splitting modules into atomic files containing only one function I can think of is that it solves circular imports for good. The only way to create a circular import with 1-to-1 function module mappings is a recursion. Note that such a circular import would actually be a bug, as the design suggests the functions being modular (compare: modules) when they are actually tightly coupled. So, the error about the circular import becomes a valuable signal to move these functions to the same module so that the design reflects their tight coupling.

- Yes, `import numpy as np` is very common. Notice though that it introduces the term `np`, which is not the name of the numpy project on PyPI and thus, the importer implicitly takes on responsibility for not also importing [np from PyPI](https://pypi.org/project/np/), which adds maintainability burden. This is not theoretical, as people `import matplotlib as mp` ([mp on PyPI](https://pypi.org/project/mp/)), `import plotly as px` ([px on PyPI](https://pypi.org/project/px/)) and so on.

**Comment by Bengt** [comment]
I spent some time fixing up the PyInstaller scripts. I was able to build all packages, but the GUI one does not seem to work completely.

**Comment by Bengt** [comment]
The PyInstaller builds now work in CI und Linux:

<https://github.com/Bengt/BirdNET-Analyzer/actions/runs/5671800770/job/15369669489>

**Comment by Bengt** [comment]
The distribution of this package is now available on Test PyPI:

<https://test.pypi.org/project/birdnet/>

**Comment by Josef-Haupt** [comment]
Thanks for your work, but a lot has changed since then, gracefully closing this PR 🫡

**Pull request closed without merging**
