### PR TITLE
Update locales and added missing ones acording ebird suported locales

### PR DESCRIPTION
**Pull request by wiliamsouza**
I was looking for Brazilian portuguese `pt_BR` locales because the `pt` were not working.
But instead only add `pt_BR` or fix `pt` maybe adding support to missing locales can help others.
With that in mind this PR add support to all availabe names listed [here](https://support.ebird.org/en/support/solutions/articles/48000804865-bird-names-in-ebird ).

What do you think about document this locales on readme file?

### CODE REVIEW

**Comment by Josef-Haupt** [comment]
Hey thanks for wour work!
These are a lot of files though, I'm not sure if all of them contain a relevant number of translations. Could you check of all of these translations contain atleast 10 percent translated labels? Compared to the en default labels.

**Comment by wiliamsouza** [comment]
I used a script the following script:
```bash
#!/bin/bash
# Measures file difference percentage 
# First install wdiff
# sudo apt install wdiff

for filename in *.txt; do
    [ -e "$filename" ] || continue
        wdiff -s BirdNET_GLOBAL_6K_V2.4_Labels_en.txt $filename | tail -2
        echo "--------------------------------------------------------------------------------"
done
```

This is the result [percentage.txt](https://github.com/kahst/BirdNET-Analyzer/files/15314844/percentage.txt)

**Review by mrestivill — APPROVED** [review]

**Comment by Josef-Haupt** [comment]
Thank you, but could you do the comparison on a line by line basis? It's nice to have more languages, but we want to limit the number of label files in the repository to a certain number, that still leaves the option for users to add more languages locally.

**Comment by Josef-Haupt** [comment]
Nearly all of the existing translations get overwritten with the english default even if a translation exists. Because I can not check all of these files, I will just exclude them.
After checking all the new language files for a threshhold of atleast 10 percent translated labels compared to the english ones, that leaves me with bg, el, he, hr, in, is, lt, ml, sr
I'll create a new pr for those.

**Comment by wiliamsouza** [comment]
@Josef-Haupt Great work!
I will open a new PR for `pt_BR` translations.
I thinking about the case of languages that do not have much species occurencies.
They can not acheive 10% translate words.
For example in Brazil we have a committee named CBRO that take care of country species list and have listed only 1971 from the 6522 on translation files. Braziliam portuguese will never pass 31%!
One way to decrease the line number for translations are remove untranslated words and in case of miss when requesting a translated string fallback to `US_en`. What do you think about that sollution?

**Comment by Josef-Haupt** [comment]
Yes I just thought about that too. We might switch up how we handle translations, to handle cases like the one you described.

**Pull request closed without merging**
