### PR TITLE
Order result rows by numeric start time.

### PR DESCRIPTION
**Pull request by HaroldMills**
The rows were ordered by start time strings, which is a little different
and undesirable, e.g. a row with the start time string "2.0" came after
a row with the start time string "10.0" instead of
before it.

### CODE REVIEW

**Comment by HaroldMills** [comment]
The changes in this pull request seemed to me to be the minimal ones that would order the rows of output files correctly by chunk start time. It is not clear to me, though, why analyze.py uses timestamps that are strings of the form <start>-<end>. Would it be better to just use numeric start times instead of the strings as timestamps? Then sorting results with `sorted(r)` would do the right thing and the changes proposed in this request would not be necessary. You would need to modify the code that writes result files, however, to compute end times and format both start and end times. That seems like a more logical place for such formatting, though. I'd be happy to make such changes and submit a pull request for them if you'd like.

**Comment by HaroldMills** [comment]
Oops, in my comment "strings of the form -" should have read "strings of the form \<start>-\<end>". Sorry...

**Comment by kahst** [comment]
Good point, thanks!

**Comment by HaroldMills** [comment]
Just one more thought about this. It might make most sense to keep track of the chunk index in the results instead of the start time. You could then have short functions that compute chunk start and end times from the index, and use those wherever needed, e.g. when writing output files.

**Pull request merged**
