### PR TITLE
Updated BirdNET-Pi link

### PR DESCRIPTION
**Pull request by mcguirepr89**
Hello, I have a new domain I'd like to include here if that's alright

### CODE REVIEW

**Comment by kahst** [comment]
Sure, nice site!

**Comment by mcguirepr89** [comment]
I'd like to keep the repo link in the description, but thank you for asking!

**Comment by mcguirepr89** [comment]
I changed my mind right after saying that

**Comment by kahst** [comment]
Ok, sure, I'll make the change.

**Pull request merged**
